# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e5aa650aefccb7a6b9db6ffa72a8bbf2a0f292d2199940fb5db31ac5f30bbc95c50a896f622b79e9ff657ea28eb5f72bade9bc7410c7436325a6aab6fc5919a

test:
  secret_key_base: d44d1202c9f13d56ebb8d5f8f59ab338195c4a46ee6f1aa784ac776cdbd68977a175d5534975f936e0e26f01f328ad8cb8c321168cf4ac33de474ac9d1281599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
